# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alfmunny/Projects/EVA02

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alfmunny/Projects/EVA02

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alfmunny/Projects/EVA02/CMakeFiles /home/alfmunny/Projects/EVA02/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alfmunny/Projects/EVA02/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_logging

# Build rule for target.
test_logging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_logging
.PHONY : test_logging

# fast build rule for target.
test_logging/fast:
	$(MAKE) -f CMakeFiles/test_logging.dir/build.make CMakeFiles/test_logging.dir/build
.PHONY : test_logging/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named eva02

# Build rule for target.
eva02: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eva02
.PHONY : eva02

# fast build rule for target.
eva02/fast:
	$(MAKE) -f CMakeFiles/eva02.dir/build.make CMakeFiles/eva02.dir/build
.PHONY : eva02/fast

src/logging.o: src/logging.cpp.o

.PHONY : src/logging.o

# target to build an object file
src/logging.cpp.o:
	$(MAKE) -f CMakeFiles/eva02.dir/build.make CMakeFiles/eva02.dir/src/logging.cpp.o
.PHONY : src/logging.cpp.o

src/logging.i: src/logging.cpp.i

.PHONY : src/logging.i

# target to preprocess a source file
src/logging.cpp.i:
	$(MAKE) -f CMakeFiles/eva02.dir/build.make CMakeFiles/eva02.dir/src/logging.cpp.i
.PHONY : src/logging.cpp.i

src/logging.s: src/logging.cpp.s

.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.cpp.s:
	$(MAKE) -f CMakeFiles/eva02.dir/build.make CMakeFiles/eva02.dir/src/logging.cpp.s
.PHONY : src/logging.cpp.s

test/test_logging.o: test/test_logging.cpp.o

.PHONY : test/test_logging.o

# target to build an object file
test/test_logging.cpp.o:
	$(MAKE) -f CMakeFiles/test_logging.dir/build.make CMakeFiles/test_logging.dir/test/test_logging.cpp.o
.PHONY : test/test_logging.cpp.o

test/test_logging.i: test/test_logging.cpp.i

.PHONY : test/test_logging.i

# target to preprocess a source file
test/test_logging.cpp.i:
	$(MAKE) -f CMakeFiles/test_logging.dir/build.make CMakeFiles/test_logging.dir/test/test_logging.cpp.i
.PHONY : test/test_logging.cpp.i

test/test_logging.s: test/test_logging.cpp.s

.PHONY : test/test_logging.s

# target to generate assembly for a file
test/test_logging.cpp.s:
	$(MAKE) -f CMakeFiles/test_logging.dir/build.make CMakeFiles/test_logging.dir/test/test_logging.cpp.s
.PHONY : test/test_logging.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_logging"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... eva02"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... test/test_logging.o"
	@echo "... test/test_logging.i"
	@echo "... test/test_logging.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

